backend_url: http://backend:8000/
interval_seconds: 60
limnigrafos:
- id: 5
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTE0NzkyLCJpYXQiOjE3NjQ5MDc1OTIsImp0aSI6ImE4MmFhZjI2MTRiMDQ4YjE4ZDU5NGFhMzFjMTBkNWFmIiwidXNlcl9pZCI6IjcifQ.itjYU3vac9ytslEfkxW40p1N9qlWo8ic4G_fS7SuBZ8
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 2
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTE0NzkyLCJpYXQiOjE3NjQ5MDc1OTIsImp0aSI6ImVlMmY2Njk3ZWE5OTQxZDk4N2QzZThlYjMxMTk2ZGE4IiwidXNlcl9pZCI6IjgifQ.HRQ2kXfTbRbFtqzz8grUzT6hEaqhV4RTiY4fV2qphbE
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 6
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTE0NzkyLCJpYXQiOjE3NjQ5MDc1OTIsImp0aSI6ImYwZDQ5NGJkZjc0YzQxZmFhOGYwN2FkOTc3MGIzZGJlIiwidXNlcl9pZCI6IjkifQ.tf3dSyXzfoLzZAz_ppKsKkyUveW2pAlwRYS00b0IFcs
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.0
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 4
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTE0NzkyLCJpYXQiOjE3NjQ5MDc1OTIsImp0aSI6ImQwYzYxNjRmM2QyMjRlMTFhNWIyYjc0MTc3MjhmZTQ1IiwidXNlcl9pZCI6IjUifQ.n3Ley9Ik3B38zKBVtaF7rBsm3qVlz4h57bHGvhwtvq0
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 3
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTE0NzkyLCJpYXQiOjE3NjQ5MDc1OTIsImp0aSI6IjAyOWE0NDUzYTYyNDQ2MGY4NjIxYTdjYzg1MTYxZWEwIiwidXNlcl9pZCI6IjMifQ.Kkk3Uj8QM6SfE3Yobwo8cP99eiIiG6DRpZQV-swGwaE
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 1
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTE0NzkyLCJpYXQiOjE3NjQ5MDc1OTIsImp0aSI6ImI2NDgyNDFlY2QxZTQyYTVhMmE2YmFmY2RmNDEzNDcxIiwidXNlcl9pZCI6IjYifQ.t6_864m2BqDEiAWxGD2e9NHCrA080Ax5F2SAtx0C5eA
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 7
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTE0NzkyLCJpYXQiOjE3NjQ5MDc1OTIsImp0aSI6IjZjODI2NTI5NDY1YjRmZTVhMDU0MDIzZDhhYjFmM2U5IiwidXNlcl9pZCI6IjEwIn0.obtjtFpyNn_Dkran0Wh6zxAC3UErDSMaRA3VWWLYikk
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.0
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
