backend_url: http://backend:8000/
interval_seconds: 60
limnigrafos:
- id: 5
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTQ2NDQyLCJpYXQiOjE3NjQ5MzkyNDIsImp0aSI6IjdkNmEzNmNhM2E4NTQxNDViZjQzNWQ0MmU4MDYyY2E2IiwidXNlcl9pZCI6IjcifQ.0SYpWwskS7woF2kOm150lLvugWeNlhwTo0eFgI6bnqc
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 2
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTQ2NDQyLCJpYXQiOjE3NjQ5MzkyNDIsImp0aSI6Ijg3NzhkOThiYWNkNjQ2ZWM4YThkNDU4ZmY4N2FkYmI0IiwidXNlcl9pZCI6IjgifQ.gdMUUITgYdInGgOUGnaILVzm-UyjolRL0w6jYSAVmtk
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 6
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTQ2NDQyLCJpYXQiOjE3NjQ5MzkyNDIsImp0aSI6ImE1YWUyYmY0OWEyOTQzZDg5NDVkMjZhOWM3YWY0MTY4IiwidXNlcl9pZCI6IjkifQ.M5DYDoZjmweJRZZHw_EzMaGSnejvxxKZjgfuN3Fsqwc
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.0
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 4
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTQ2NDQyLCJpYXQiOjE3NjQ5MzkyNDIsImp0aSI6IjY2M2NiMmY3ZDQyMDQ2MTM5MzMwOTFhM2YxNjEzNjNlIiwidXNlcl9pZCI6IjUifQ.EL_pj2IPPKiCSeGCwWaSm3hqaueyZi2LWupLEzKnsTU
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 3
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTQ2NDQyLCJpYXQiOjE3NjQ5MzkyNDIsImp0aSI6ImU0NDdkNjY5NGU4ODRhMjE5MjMwYzBiN2UzMDY0MzZhIiwidXNlcl9pZCI6IjMifQ.luByA2dwdsYKewt2KeO3wAUENbmb2G31NQtw6QTWi-M
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 1
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTQ2NDQyLCJpYXQiOjE3NjQ5MzkyNDIsImp0aSI6IjI3YTQ3MWJmYjZjYjRlMDk5YWMxNzMzN2QyMjNjZmMxIiwidXNlcl9pZCI6IjYifQ.CrpatUkWEPepf4LYhJ50LNy7ODiwmTBRuvpIBybQ-vU
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 7
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTQ2NDQyLCJpYXQiOjE3NjQ5MzkyNDIsImp0aSI6IjI2MzU4ZTQ5Y2JjODQyNTNhN2JmNjg5ZGE3OTE2M2Y0IiwidXNlcl9pZCI6IjEwIn0.3wMbXaCbM21_TTJxeUMk_dNumsWk_nv2AX7eDZBblsc
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.0
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
