backend_url: http://backend:8000/
interval_seconds: 300
limnigrafos:
- id: 5
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTA1OTA5LCJpYXQiOjE3NjQ4OTg3MDksImp0aSI6IjQzY2I1NGVjYTk3NDRlOThhNjBmM2U3YzNhNDkxYTAwIiwidXNlcl9pZCI6IjcifQ.2WH8kXD7jgzQTgSSV8K3Wp0kqzWlNpuDmW4n6bfU-zo
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 2
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTA1OTA5LCJpYXQiOjE3NjQ4OTg3MDksImp0aSI6IjA0OWFhZTA3NjM3NjRkYmZiZTQzMzZiZjQ3YWJkOGIyIiwidXNlcl9pZCI6IjgifQ.9hId8ssKmBulxW1IkhoUKpmh6yvthPG-OURH3VuBPPA
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 6
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTA1OTA5LCJpYXQiOjE3NjQ4OTg3MDksImp0aSI6IjI5MzhhYzE0MDJlMDQ0YzI4NWRmNjhjZDkxMzFhYTZmIiwidXNlcl9pZCI6IjkifQ.ocVPlUhrZi46HMLxPv9ADMvLTdROALsalGyopa1WqMQ
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.0
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 4
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTA1OTA5LCJpYXQiOjE3NjQ4OTg3MDksImp0aSI6IjhhNmM1MDBlN2ZjZTQ5OWI5OWY4M2E4NzZiNWIzNmVjIiwidXNlcl9pZCI6IjUifQ.rI6mXE5Eyk0jVySKfBbzH9t-vh8DiZEv5b-IFfb7dUU
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 3
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTA1OTA5LCJpYXQiOjE3NjQ4OTg3MDksImp0aSI6ImM2ODNjNjA3ZDNkZDQ2NDA4ZGZkZDE0NzNlMTc0YzBlIiwidXNlcl9pZCI6IjMifQ.Q69Q2oPmSqeMBqfEZmpDOpAx6_2dmA9EmtIEStq4RdQ
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 1
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTA1OTA5LCJpYXQiOjE3NjQ4OTg3MDksImp0aSI6Ijc4OTYxYjg2OTViMzQ5Nzg5MjZlOTE4YjVmNDQ3MGNiIiwidXNlcl9pZCI6IjYifQ.2t8aZXaX8k6KGB5kUHVz0OJl93ZErVY9umYcG1pGf5o
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.5
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
- id: 7
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTA1OTA5LCJpYXQiOjE3NjQ4OTg3MDksImp0aSI6IjQ5NzJkYmVkODIwMTQ5ZTZhMzIzNGExZTUxN2VjNDU5IiwidXNlcl9pZCI6IjEwIn0.gAOgkM6A8h3WGULPjwHSIGLsoIK0PA8se8Z_E_c7y80
  altura_min: 0.5
  altura_max: 3.5
  temperatura_min: -5
  temperatura_max: 25
  presion_min: 950
  presion_max: 1050
  bateria_min: 10.0
  bateria_max: 13.0
  probabilidad_falla: 0.1
  duracion_falla_min: 20
